name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container: igoticecream/devkitpro
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set environment variables
        run: echo ::set-env name=LIBNX::"$GITHUB_WORKSPACE/lib/libnx/nx"
      - name: Check dir
        run: |
          pwd $LIBNX
          ls $LIBNX
      - name: Build Libnx
        run: make -j$(nproc) -C lib/libnx
      - name: Build Homebrew
        run: make -j$(nproc)
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: test.nro
