name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    container: igoticecream/devkitpro
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Libnx
        working-directory: lib/libnx
        run: make -j$(nproc)
      - name: Build App
        working-directory: .
        run: make -j$(nproc)
